export type AmenitiesType =
  | "Wifi"
  | "Heating"
  | "Air Conditioning"
  | "Washer"
  | "Dryer"
  | "Iron"
  | "Essentials"
  | "HotWater"
  | "TV"
  | "Refrigerator"
  | "Microwave"
  | "CoffeeMaker"
  | "Cooking Basics"
  | "Oven"
  | "Stove"
  | "Dishwasher"
  | "Dishes And Silverware"
  | "Kitchen"
  | "Smoke Alarm"
  | "CarbonMonoxideAlarm"
  | "FirstAidKit"
  | "FireExtinguisher"
  | "BedroomLock"
  | "HighChair"
  | "BabySafetyGates"
  | "BabysitterRecommendations"
  | "FreeParkingOnPremises"
  | "PaidParkingOffPremises"
  | "PaidParkingOnPremises"
  | "Elevator"
  | "WheelchairAccessible"
  | "BbqGrill"
  | "PatioOrBalcony"
  | "GardenOrBackyard"
  | "PrivateEntrance"
  | "Gym"
  | "Pool"
  | "HotTub"
  | "Sauna"
  | "LongTermStaysAllowed"
  | "LuggageDropoffAllowed"
  | "CleaningBeforeCheckout"
  | "PetsAllowed"
  | "BoardGames"
  | "BooksAndReadingMaterial"
  | "SmartTV"
  | "DedicatedWorkspace";

export type AmenitiesGroupType =
  | "Basic"
  | "Kitchen"
  | "Safety"
  | "Family"
  | "Parking_and_Accessibility"
  | "Outdoor"
  | "Fitness"
  | "Additional"
  | "Pets"
  | "Entertainment";
