export type AmenitiesType =
  | "Wifi"
  | "Sea view"
  | "Mountain view"
  | "Courtyard view"
  | "Hair Dryer"
  | "Cleaning Products"
  | "Dishwasher"
  | "Heating"
  | "Air Conditioning"
  | "Sun Lounge"
  | "Washer"
  | "Dryer"
  | "Iron"
  | "Essentials"
  | "Hot Water"
  | "TV"
  | "Refrigerator"
  | "Microwave"
  | "CoffeeMaker"
  | "Cooking Basics"
  | "Oven"
  | "Stove"
  | "Dishes And Silverware"
  | "Kitchen"
  | "Smoke Alarm"
  | "Carbon Monoxide Alarm"
  | "First Aid Kit"
  | "Fire Extinguisher"
  | "Bed Linens"
  | "High Chair"
  | "Free Parking On Premises"
  | "Paid Parking Off Premises"
  | "Paid Parking On Premises"
  | "Elevator"
  | "Bbq Grill"
  | "Patio Or Balcony"
  | "GardenOrBackyard"
  | "PrivateEntrance"
  | "HotTub"
  | "Sauna"
  | "Luggage Dropoff Allowed"
  | "Smart TV"
  | "Dedicated Workspace";

export type AmenitiesGroupType =

  | "Entertainment"
  | "Scenic views"|"Bathroom"|"Bedroom and laundry"|"Essentials"
