export type Labels =
  | "icons"
  | "amazing views"
  | "omg!"
  | "beachfront"
  | "ski in out"
  | "top cities"
  | "amazing pools"
  | "countryside"
  | "castles"
  | "cabins"
  | "trending"
  | "off the grid"
  | "farms"
  | "lakefront"
  | "design"
  | "lake"
  | "tiny homes"
  | "tree houses"
  | "islands"
  | "mansions"
  | "luxe"
  | "national parks"
  | "top of the world"
  | "tropical"
  | "play"
  | "historical homes"
  | "boats"
  | "new"
  | "earth homes"
  | "caves"
  | "desert"
  | "chef s kitchens"
  | "vineyards"
  | "bed & breakfasts"
  | "skiing"
  | "camping"
  | "a frames"
  | "domes"
  | "surfing"
  | "towers"
  | "yurts"
  | "ryokans"
  | "houseboats"
  | "creative spaces"
  | "arctic"
  | "cycladic homes"
  | "trulli"
  | "grand pianos"
  | "rooms"
  | "containers"
  | "windmills"
  | "dammusi"
  | "casas particulares"
  | "shepherd s huts"
  | "minsus"
  | "campers"
  | "golfing"
  | "hanoks"
  | "barns"
  | "adapted"
  | "riads"
  | "beach";
